# Generated by Django 5.0.2 on 2024-05-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko_susu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailpembelian',
            options={'verbose_name_plural': '5. Detail Pembelian'},
        ),
        migrations.AlterModelOptions(
            name='pelanggan',
            options={'verbose_name_plural': '3. Pelanggan'},
        ),
        migrations.AlterModelOptions(
            name='pemasok',
            options={'verbose_name_plural': '1. Pemasok'},
        ),
        migrations.AlterModelOptions(
            name='pembelian',
            options={'verbose_name_plural': '4. Pembelian'},
        ),
        migrations.AlterModelOptions(
            name='produksusu',
            options={'verbose_name_plural': '2. Produk Susu'},
        ),
    ]
